author: "殷啟聰 | Kai-Chung Yan"
permalink: blog/posts/:title.html
timezone: UTC
title: Blog by seamlik
url: https://seamlik.github.io

deploy:
  type: git
  branch: master
  repo: git@github.com:seamlik/seamlik.github.io.git

feed:
  type: atom

theme: default