author: "殷啟聰 | Kai-Chung Yan"
permalink: post/:title.html
title: Blog by seamlik
url: https://seamlik.github.io
disqus_shortname: seamlik-blog-github

deploy:
  type: git
  branch: master
  repo: git@github.com:seamlik/seamlik.github.io.git

theme: landscape
theme_config:
  favicon: img/favicon.ico
  menu:
    Home: /
    Archives: /archives
    About: /about.html