baseURL = "https://seamlik.github.io"
defaultContentLanguage = "en"
disqusShortname = "seamlik-blog-github"
languageCode = "en-us"
theme = "beautifulhugo"
title = "Blog by seamlik"

[Params]
  favicon = "img/favicon.ico"
  logo = "img/logo.png"

[Author]
  github = "seamlik"
  gitlab = "seamlik"
  linkedin = "seamlik"
  name = "殷啟聰 | Kai-Chung Yan"
  twitter = "seamlik"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2